name: FastAPI Docker CI

on:
  push:
    branches: [main]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

        

      - name: Install dependencies
        run: pip install -r requirements.txt

      # 1️⃣ Build the Docker image
      - name: Build Docker image
        run: docker build -t mock-api:test .

      # 2️⃣ Start containers using that image
      - name: Start services
        run: docker compose up -d

      # 3️⃣ Wait for services
      - name: Wait for API
        run: sleep 10

      # 4️⃣ Create database tables
      - name: Setup database
        run: docker exec fastapi_app python setup_db_tables.py

        

      # 5️⃣ Run tests
      - name: Run tests
        run: pytest -v

      # 6️⃣ Tag the SAME tested image
      - name: Tag Docker image
        run: docker tag mock-api:test ${{ secrets.DOCKER_USERNAME }}/mock-api:latest

      # 7️⃣ Push it
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mock-api:latest